### ISSUE TITLE
WIP - Requires testing + removing .patch needs

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-npc-talent-template#1]
This module is really really interesting. Sadly it requires a .patch actually

@Nefertumm tried to make it work without the .patch, here is the file: https://cdn.discordapp.com/attachments/403595102267899915/452203429838848010/TemplateNPC.cpp

But @motorheadx tested and said it was buggy

@renatokeys said the module was bugged from the start

So all in all this module requires testing + removing the need for the .patch

PS: @mindsear is the author and he has right access on this repository

**Comment by mindsear** [comment]
Sorry for the late response, I will try to take a look again, although I have tested with one rogue character and it was working.

**Comment by BarbzYHOOL** [comment]
Ok, when I have time I plan to test it in depth if no one has done it prior to that

**Comment by talamortis** [comment]
What does this module do?

**Comment by mindsear** [comment]
> What does this module do?

![](https://image.ibb.co/koobrd/template_Npc.png)  

Video Showcase:
https://streamable.com/yxv1m

**Comment by BarbzYHOOL** [comment]
it's shown 0.5 sec in the video but it also teaches talents etc

**Comment by BarbzYHOOL** [comment]
Also @mindsear you didn't accept invitation (nor decline) for this repository

**Comment by mindsear** [comment]
I didn't get an invitation. 
Wouldn't be better if you erase this and clone it, make it your own in order to have write/pull permissions?
As you may know, I'm not the creator of this script, I just updated for tc and converted to azerothcore.

**Comment by BarbzYHOOL** [comment]
>Wouldn't be better if you erase this and clone it, make it your own in order to have write/pull permissions?

? I don't get it

I reinvited you and here is the invitation link: https://github.com/azerothcore/WIP-mod-npc-talent-template/invitations

And no, I didn't know that the script existed before (but it's not that important :P)

**Comment by BarbzYHOOL** [comment]
Ok, some people tested it successfully, it just needs to remove the .patch with extra or existing hooks

**Comment by poszer** [comment]
https://github.com/azerothcore/mod-npc-talent-template/issues/6

**Comment by mindsear** [comment]
> Ok, some people tested it successfully, it just needs to remove the .patch with extra or existing hooks

I will try to make it without a patch next weekend.

**Comment by mindsear** [comment]
Modified TemplateNPC.cpp file to work without the .patch thingy || Also, added option to disable gear template as suggested by BarbzYHOOL https://github.com/azerothcore/mod-npc-talent-template/issues/3

https://gist.github.com/mindsear/32efc742bd341856deb6ad463c3b99c6

**Comment by BarbzYHOOL** [comment]
Awesome, did you include this in the PR ? (sorry I am not very active these days but I will try it if nobody does) @mindsear 

https://github.com/azerothcore/mod-npc-talent-template/pull/7

Also, you have been invited as I said before, here is the link https://github.com/azerothcore/mod-npc-talent-template/invitations

**Comment by BarbzYHOOL** [comment]
Btw I'm surprised you didn't need to add anything to AC to make it work without the patch

**Comment by mindsear** [comment]
Out of laziness I took the code made by @Nefertumm and tweaked it a bit to make it work with the latest AC. So, all credit goes to him.

**Comment by BarbzYHOOL** [comment]
Awesome, at least none work was wasted in the process !

**Comment by BarbzYHOOL** [comment]
Closed with https://github.com/azerothcore/mod-npc-talent-template/commit/a4156ec9456731441c4a3a7f7b32c718e875c9cf
