### ISSUE TITLE
items are equipped to characters head

### ISSUE THREAD

**Issue by disclosurez** [azerothcore/mod-npc-talent-template#10]
Upon trying to use the template npc, only one item is equipped to there head

**Comment by disclosurez** [comment]
https://i.imgur.com/QpePYI5.jpg

example pic

**Comment by poszer** [comment]
> Upon trying to use the template npc, only one item is equipped to there head

Can't reproduce. 
http://prntscr.com/nudbfz
It's problem from your side for sure

**Comment by milestorme** [comment]
cannot reproduce either

**Comment by disclosurez** [comment]
I get this message when trying to use the npc

Player(GUID: 2003 Name: Dasdasd)::_SaveInventory - the bag(255) and slot(0) values for the item with guid 2010975 are incorrect, the item with guid 2010978 is there instead!


anyone know of a fix for this?

**Comment by disclosurez** [comment]
here is how to fix:


ALTER TABLE `template_npc_glyphs`
	CHANGE COLUMN `glyph` `glyph` MEDIUMINT UNSIGNED NOT NULL DEFAULT '0' AFTER `slot`;

ALTER TABLE `template_npc_human`
	CHANGE COLUMN `pos` `pos` TINYINT UNSIGNED NOT NULL DEFAULT '0' AFTER `playerSpec`;

ALTER TABLE `template_npc_horde`
	CHANGE COLUMN `pos` `pos` TINYINT UNSIGNED NOT NULL DEFAULT '0' AFTER `playerSpec`;


ALTER TABLE `template_npc_alliance`
	CHANGE COLUMN `pos` `pos` TINYINT UNSIGNED NOT NULL DEFAULT '0' AFTER `playerSpec`;

**Comment by BarbzYHOOL** [comment]
you changed it from what to what ? also use 3 ` to put on github
