### ISSUE TITLE
Character stats, spells, talents

### ISSUE THREAD

**Issue by Zausender** [azerothcore/mod-npc-talent-template#13]
- Doesn't work correct. When you use this NPC in game, and get Gear and Talents, your character have 40k HP with S7 gear :rofl: 
When you remove gear, you still have 40k HP haha.
Also, when you learn spells, for example Priest spell Inner Fire will give you 44 charges xD
https://image.prntscr.com/image/Gau_qWjTQHOnOPNsBADhyA.png
Also, when you use mass dispel it's instant cast. 
Everything wrong with this module.

**Comment by BarbzYHOOL** [comment]
your link is 404

> Everything wrong with this module.

Not the best way to encourage the author to fix it.

**Comment by Zausender** [comment]
> your link is 404
> 
> > Everything wrong with this module.
> 
> Not the best way to encourage the author to fix it.

i added image link to show bug with priest inner fire buff (stack is 44) but its removed dont know why. Attaching image now here directly
![innerfire](https://user-images.githubusercontent.com/56157973/66611443-d9173080-ebbe-11e9-9569-6be413c2251f.png)

**Comment by xilmen** [comment]
I have a same problem

**Comment by pangolp** [comment]
Does this problem still persist?

**Comment by xilmen** [comment]
you can close a think,
