### ISSUE TITLE
[Conflict] Same NPC ID's

### ISSUE THREAD

**Issue by Knindzagxg** [azerothcore/mod-npc-talent-template#14]
If members decide to use module NPC Services there will be conflict between ID's since both modules using same at the moment.

https://github.com/azerothcore/mod-npc-services/blob/master/sql/world/Npc_Services.sql

**Comment by BarbzYHOOL** [comment]
ok easy to change, you could do it knindza xD

@Knindzagxg  can you change it to another ID because you listed all the IDs few minutes ago so you know which one not to use

https://github.com/azerothcore/mod-npc-talent-template/edit/master/sql/characters/characters.sql

**Comment by BarbzYHOOL** [comment]
i put a new number in my PR too https://github.com/azerothcore/mod-npc-talent-template/pull/16

**Comment by pangolp** [comment]
I'm going to close this pull request, because it's from the year 2020. Please, if you think I'm wrong and the issue you're talking about still persists, let me know and we'll deal with it again. I want to try to keep the repository clean and wait for new issues or pull requests.
