### ISSUE TITLE
Prismatic socket in the belt

### ISSUE THREAD

**Issue by arenacraftwow** [azerothcore/mod-npc-talent-template#19]
Belt prismatic socket bonuses don't get applied. After I relog everything gets applied correctly. 

First login, using the NPC
![image](https://user-images.githubusercontent.com/61932925/78360336-f00b6e00-75b6-11ea-8023-6b725e340102.png)

After relog
![image](https://user-images.githubusercontent.com/61932925/78360366-fbf73000-75b6-11ea-9b1b-4c393c012e90.png)

Notice: I gain exactly 12 spell power.

**Comment by BarbzYHOOL** [comment]
maybe it's client side only?

**Comment by arenacraftwow** [comment]
@BarbzYHOOL Looking at the code it seems like its a server side issue, unlikely a client thing.

**Comment by ErnestoGonzalezC** [comment]
https://github.com/azerothcore/mod-npc-talent-template/pull/28 fixed

**Comment by ErnestoGonzalezC** [comment]
now everything should work correctly :)

**Comment by ErnestoGonzalezC** [comment]
https://github.com/azerothcore/mod-npc-talent-template/pull/31 Fixed
