### ISSUE TITLE
Suggestion - Scaling for twink servers

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-npc-talent-template#2]
The template could be adaptable or semi-adaptable (with a bit of manual modification) to set talents for low level characters and not only lvl 80 characters

**Comment by mindsear** [comment]
I don't think this would be a hard thing to do, it's just a time consuming process.

**Comment by BarbzYHOOL** [comment]
maybe with a database driven configuration it could be much quicker

with some smart queries we could get the needed spells and not write them down in the c++ and make the script huge @mindsear

**Comment by pangolp** [comment]
To be able to do this, it would have to be structured possibly in the database, allowing people to add different records and adapt them to each server.
