### ISSUE TITLE
Bug when granting talents

### ISSUE THREAD

**Issue by ghost** [azerothcore/mod-npc-talent-template#25]
the npc contains 1 bug in the talents section, let me explain. When equipping any character, for example a magician, some kind of bug occurs in the talents that causes the haste to increase in a beastly way.
The same with the shaman but in this case what happens is that the chain of lightning has practically no cooldowns (only one second = global cooldown)
Here is an example photo.
<img src="https://raw.githubusercontent.com/ErnestoGonzalezC/test/main/WoWScrnShot_020821_172551.jpg"></img>

**Comment by pangolp** [comment]
I'm going to close this pull request, because it's from the year 2020. Please, if you think I'm wrong and the issue you're talking about still persists, let me know and we'll deal with it again. I want to try to keep the repository clean and wait for new issues or pull requests.
