### ISSUE TITLE
Broken since last major changes of AC

### ISSUE THREAD

**Issue by jpaechnatz** [azerothcore/mod-npc-talent-template#33]
Causes an compiler error since last major changes in AC.

**Comment by Helias** [comment]
what are the errors?

@ultranix ?

**Comment by UltraNix** [comment]
I don't see any conflicts related to ObjectGuid implementation.

**Comment by jpaechnatz** [comment]
Tried compiling again for better error report, thats in what I can capture from my console....:

/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:170:7: note: candidate function
      operator<<(unsigned long __n)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:174:7: note: candidate function
      operator<<(bool __n)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:178:7: note: candidate function
      operator<<(short __n);
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:181:7: note: candidate function
      operator<<(unsigned short __n)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:189:7: note: candidate function
      operator<<(int __n);
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:192:7: note: candidate function
      operator<<(unsigned int __n)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:201:7: note: candidate function
      operator<<(long long __n)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:205:7: note: candidate function
      operator<<(unsigned long long __n)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:220:7: note: candidate function
      operator<<(double __f)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:224:7: note: candidate function
      operator<<(float __f)
      ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../../include/c++/10/ostream:232:7: note: candidate function
      operator<<(long double __f)
      ^
1 error generated.
make[2]: *** [src/server/scripts/CMakeFiles/scripts.dir/build.make:8378: src/server/scripts/CMakeFiles/scripts.dir/__/__/__/modules/mod-npc-talent-template/src/TemplateNPC.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:1206: src/server/scripts/CMakeFiles/scripts.dir/all] Error 2
make: *** [Makefile:149: all] Error 2

**Comment by Helias** [comment]
locally I got this
```C++
fatal error: use of overloaded operator '<<' is ambiguous (with operand types 'std::basic_ostream<char>' and 'const ObjectGuid')
```

**Comment by Helias** [comment]
fixed https://github.com/azerothcore/mod-npc-talent-template/pull/34
