### ISSUE TITLE
"There's no templates for % specialization yet"

### ISSUE THREAD

**Issue by SaidKing** [azerothcore/mod-npc-talent-template#39]
When adding the NPC in the game, it doesn't do the function, it just appears this message above, "There are still no templates for % of specialization". How can I fix it? Is it necessary to enable Gossip on the NPC?

[https://ibb.co/Hn1zFbd](url)

**Comment by ronxmag** [comment]
yeah your right something wrong with templateNPC since the update hope they can fix it 

Please take a look on my actual screenshot of the template npc is not working at all! 

![templatenpc](https://user-images.githubusercontent.com/55305997/163969748-50303224-100f-46b6-99fd-10469b296777.png)

Hoping that anyone knowledgeable to fix this issues thanks in advance!

**Comment by Diablosstars** [comment]
Use commit 13a4890 until the pull request is approved. Output for worldserver should be similar to the image below. @SaidKing  @ronxmag 

![image](https://user-images.githubusercontent.com/17943592/165227403-9410087e-56c2-4137-bf58-0698bb5b5775.png)

**Comment by ronxmag** [comment]
> Use commit [13a4890](https://github.com/azerothcore/mod-npc-talent-template/commit/13a4890da03fd8ca85b8cb07657258490ff9628d) until the pull request is approved. Output for worldserver should be similar to the image below. @SaidKing @ronxmag
> 
> ![image](https://user-images.githubusercontent.com/17943592/165227403-9410087e-56c2-4137-bf58-0698bb5b5775.png)

WOW thanks so much for quick fix on this issue!!! excellent work Diablosstars!!! i tested it and works 100%! WOW!!

**Comment by SaidKing** [comment]
> Use commit [13a4890](https://github.com/azerothcore/mod-npc-talent-template/commit/13a4890da03fd8ca85b8cb07657258490ff9628d) until the pull request is approved. Output for worldserver should be similar to the image below. @SaidKing @ronxmag
> 
> ![image](https://user-images.githubusercontent.com/17943592/165227403-9410087e-56c2-4137-bf58-0698bb5b5775.png)

when passing in cmake I got the following error: /azerothcore/modules/mod-npc-talent-template/src/TemplateNPC.cpp:412:9: fatal error: use of undeclared identifier 'LOG_WARN'
        LOG_WARN("sql.sql", ">>TEMPLATE NPC: Loaded 0 talent templates. Database table `template_npc_talents` is empty!");
        ^

**Comment by pangolp** [comment]
Does this problem still continue?

**Comment by pangolp** [comment]
Confirmed, now I make a pull request to fix it.

![image](https://github.com/azerothcore/mod-npc-talent-template/assets/2810187/2190f7a5-7ea1-4d5f-ac13-13ecc820ba8c)
