### ISSUE TITLE
NPC is not interactable.

### ISSUE THREAD

**Issue by heyitsbench** [azerothcore/mod-npc-talent-template#42]
NPC is not interactable and doesn't have the chat icon when hovering over them. This issue is resolved by setting the `npcflag` column to 1, though due to [this commit](https://github.com/azerothcore/mod-npc-talent-template/commit/b858b44056a812872623b06dc6d1b3bd633a8293), I'm under the impression that this is not a good solution for the issue.

**Comment by pabshazon** [comment]
same here. also tried changing npcflag to 1 in db but no success

**Comment by vurtne** [comment]
same here
