### ISSUE TITLE
Infos

### ISSUE THREAD

**Issue by poszer** [azerothcore/mod-npc-talent-template#6]
### Working
1.  The Gear is applied correct
2. Glyphs are applied correct
3. The mount is learned 
4. Skills are learned 

### Doesn't work 

1.  The talents are not applied

**Comment by mindsear** [comment]
I will test it tomorrow if I can.

**Comment by poszer** [comment]
> I will test it tomorrow if I can.

Nice. The orginal code shouold be used to learn talets

**Comment by poszer** [comment]
Tested, everything is fine. Thank you @mindsear
