### ISSUE TITLE
Chores to do

### ISSUE THREAD

**Issue by BarbzYHOOL** [azerothcore/mod-npc-talent-template#9]
- [ ] Rename to character_template the module and all related files (to be less confusing and less generic)
- [ ] Add a config file and remove that config.sh.dist (or move it to another dir??)

**Comment by mindsear** [comment]
The second one can be solved by doing the following:
Remove this line
> AC_ADD_CONFIG_FILE("${CMAKE_CURRENT_LIST_DIR}/conf/TemplateNPC.conf.dist")

from **mod-npc-talent-template\CmakeLists.txt**

I'll be working on the first one.

**Comment by BarbzYHOOL** [comment]
ok but need to do it on the branch I pushed first else it will have big conflicts

I'm waiting to read your answers first

**Comment by pangolp** [comment]
I'm going to close this pull request, because it's from the year 2019. Please, if you think I'm wrong and the issue you're talking about still persists, let me know and we'll deal with it again. I want to try to keep the repository clean and wait for new issues or pull requests.
